### ISSUE TITLE
After running pod install, I'm missing some files in lcl.h

### ISSUE THREAD

**Issue by kutakmir** [Developer-ReCap-Autodesk/iOS#2]
like  "lcl_config_logger.h"

**Comment by cyrillef** [comment]
After running pod install, lcl_configure will be available at Pods/LibComponentLogging-pods/configure/lcl_configure
per the LibComponentLogging-pods, you need to run lcl_configure pod to create the files. I'll add this to the steps to perform in the readme or add a pod step which will make it easier for people.

**Comment by cyrillef** [comment]
Actually it was already document at step4
